# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

all:
  menus:
    backend_menu:
      name: Empresa
      children: 
        units:
          label: Units
          route: unit/index
        projects:
          label: Projects
          route: project/index
        members:
          label: Members
          route: member/index
        teams:
          label: Teams
          route: team/index
        