# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

all:
  menus:
    frontend_menu:
      name: Empresa
      children: 
        casa:
          label: home
          route: static/home
        projects:
          label: projects
          route: project/index
        services:
          label: services
          route: static/services
        team:
          label: team
          route: static/team
        contact:
          label: contact
          route: static/contact
