generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Unit
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          unit
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:      List of units
        display:    [ name, url, image ]
      filter:
        display:    [ name, url, image ]
      form:    ~
      edit:
        title:      Edit unit '%%name%%'
      new:
        title:      New unit
