generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Project
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          project
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:      List of projects
        display:    [ name, position, active, logo, begin_date, end_date ]
        fields:
          begin_date:     { label: Begin, date_format: dd/MM/y }
          end_date:       { label: End, date_format: dd/MM/y }
      filter:
        display:    [ name, logo, begin_date, end_date ]
      form:    ~
      edit:
        title:      Edit project '%%name%%'
      new:
        title:      New project